package com.csye6225.fall2018.courseservice.datamodel;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

/*
Announcements
     - Id (Dynamo Db generated) and hash key
     - announcementId - dynamodb Index range key part of the GSI
     - announcementText - (ensure text size is no more than 160 characters)
     - boardId -DynamoDbIndexHashKey, part of the GSI Global Secondary Index (GSI)
     - courseId - to send notification
*/

@DynamoDBTable(tableName = "Announcement")
public class Announcement {

    private String id;
    private String announcementId;
    private String announcementText;
    private String boardId;
    private String courseId;

    public Announcement() {

    }

    public Announcement(String announcementId, String announcementText, String boardId, String courseId) {
    		this.announcementId = announcementId;
    		this.announcementText = announcementText;
    		this.boardId = boardId;
    		this.courseId = courseId;
  	}

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexRangeKey(attributeName="announcementId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getAnnouncementId() {
        return announcementId;
    }

    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName="announcementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBIndexHashKey(attributeName="boardId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
}