package com.csye6225.fall2018.courseservice.datamodel;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

/*
Registrar -
       RegistrationId
       OfferingId
       OfferingType (Course, Counseling)
       Department
       PerUnitPrice (number, in USD)
*/

@DynamoDBTable(tableName = "Registrar")
public class Registrar {

    private String id;
    private String registrationId;
    private String offeringId;
    private String offeringType;
    private String department;
    private double perUnitPrice;

    public Registrar() {

    }

    public Registrar(String registrationId, String offeringId, String offeringType,
                      String department, double perUnitPrice) {
        this.registrationId = registrationId;
    		this.offeringId = offeringId;
    		this.offeringType = offeringType;
    		this.department = department;
    		this.perUnitPrice = perUnitPrice;
  	}

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String Id) {
        this.id = Id;
    }

    // @DynamoDBAttribute(attributeName = "registrationId")
    @DynamoDBIndexHashKey(attributeName = "registrationId", globalSecondaryIndexName = "registrationId-index")
    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    @DynamoDBAttribute(attributeName = "offeringId")
    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }

    @DynamoDBAttribute(attributeName = "offeringType")
    public String getOfferingType() {
        return offeringType;
    }

    public void setOfferingType(String offeringType) {
        this.offeringType = offeringType;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "perUnitPrice")
    public double getPerUnitPrice() {
        return perUnitPrice;
    }

    public void setPerUnitPrice(int perUnitPrice) {
        this.perUnitPrice = perUnitPrice;
    }
}